### ISSUE TITLE
Start script fails

### ISSUE THREAD

**Issue by sadovnik** [andrewngu/sound-redux#70]
Output:
```
/Users/cyril/sound-redux (master) $ npm run start

> sound-redux@1.0.0 start /Users/cyril/sound-redux
> webpack-dev-server --progress --colors --hot --content-base ./server/public --config ./webpack.config.js

 70% 1/1 build modules[HPM] Proxy created: /api  ->  http://localhost:8081
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1227:14)
    at listen (net.js:1263:10)
    at net.js:1372:9
    at nextTickCallbackWith3Args (node.js:486:9)
    at process._tickCallback (node.js:392:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)
    at node.js:1001:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! sound-redux@1.0.0 start: `webpack-dev-server --progress --colors --hot --content-base ./server/public --config ./webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sound-redux@1.0.0 start script 'webpack-dev-server --progress --colors --hot --content-base ./server/public --config ./webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sound-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --progress --colors --hot --content-base ./server/public --config ./webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sound-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sound-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cyril/sound-redux/npm-debug.log
```
Any ideas?

**Comment by andrewngu** [comment]
Looks like you currently have something running on port 8080?

**Comment by sadovnik** [comment]
Oh, that was stupid of me. Sorry!

**Comment by yxuecheng** [comment]
how to fix

**Comment by sadovnik** [comment]
@yxuecheng use different port or free up `8080`.

**Comment by yxuecheng** [comment]
yes，you are right ，thankyou。

发自我的 iPhone
